language: c

os:
  - linux
  - osx

services:
  - docker
  
before_install:
  - [ "$TRAVIS_OS_NAME" == "osx" ] && brew update
  - [ "$TRAVIS_OS_NAME" == "osx" ] && brew install ponyc pony-stable

script:
  - [ "$TRAVIS_OS_NAME" == "linux" ] && docker-compose build --build-arg MAX_NUM=10
  - [ "$TRAVIS_OS_NAME" == "osx" ] && ponyc && ./pony_lua_parallel
