version: 1.0.{build}
image: Visual Studio 2019
install:
- cmd: >-
    cinst /y wget unzip

    if %errorlevel% neq 0 exit /b %errorlevel%

    refreshenv

    wget -q https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/ponyc-x86-64-pc-windows-msvc.zip

    if %errorlevel% neq 0 exit /b %errorlevel%

    unzip --qq -o ponyc-0.33.1-win64.zip

    if %errorlevel% neq 0 exit /b %errorlevel%

build_script:
- cmd: >-
    set PATH=%PATH%;ponyc-0.33.1-win64\ponyc\bin

    ponyc

    if %errorlevel% neq 0 exit /b %errorlevel%

test_script:
- cmd: >-
    set PATH=%PATH%;deps\lua\windows

    set MAX_NUM=30

    .\pony-lua-parallel.exe

    if %errorlevel% neq 0 exit /b %errorlevel%
